CREATE TABLE Teams (
    Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    Name VARCHAR(MAX) NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE Participants (
    Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    Forename VARCHAR(MAX) NOT NULL,
    Surname VARCHAR(MAX) NOT NULL,
    Email VARCHAR(MAX) NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    TeamId INT FOREIGN KEY REFERENCES Teams(Id)
);

CREATE TABLE Tokens (
    Id INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    [Value] VARCHAR(MAX) NOT NULL,
    IsValid BIT NOT NULL DEFAULT 1,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    TeamId INT FOREIGN KEY REFERENCES Teams(Id),
    ParticipantId INT FOREIGN KEY REFERENCES Participants(Id),
);
