CREATE TABLE GitHubAccounts (
    Id INT PRIMARY KEY NOT NULL IDENTITY(1,1),
    Repository VARCHAR(MAX) NOT NULL,
    IssuesCopied INT DEFAULT 0,
    IsIssueCopyComplete BIT DEFAULT 0,
    LinkedAt DATETIME NOT NULL DEFAULT GETDATE()
);