name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup .NET CORE
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.x
        
      - name: Build
        run: dotnet build Site/Site.sln -c Release
        
      - name: Register Recursive Test Searcher
        run: chmod +x Site/scripts/shell/test-dir.sh
        
      - name: Run Unit Tests
        run: Site/scripts/shell/test-dir.sh Site/tests/units/
        
      - name: Run Integration Tests
        run: Site/scripts/shell/test-dir.sh Site/tests/intergration/
        
      - name: Run Acceptance Tests
        run: Site/scripts/shell/test-dir.sh Site/tests/acceptance/
        
      
        
      



